name: 'action app'
description: 'this app will print out a bunch of files in a given path...'
author: '@tbal999'

inputs:
  one:
    description: 'arg 1'
    required: true
    default: './'

runs:
    using: 'composite'
    steps:
    - run: go run ${{ github.action_path }}/actionapp.go ${{ inputs.one }} ${{ secrets.secret1 }} ${{ secrets.secret2 }}
      shell: bash
    
