name: 'action app'
description: 'this app will print out a bunch of files in a given path...'
author: '@tbal999'

inputs:
  path:
    description: 'Repo Path'
    required: true
    default: './'
  key:
    description: 'User'
    required: true
    default: '???'
  space:
    description: 'API Key'
    required: true
    default: '???'

runs:
    using: 'composite'
    steps:
    - run: export GO111MODULE=on; go mod init github.com/tbal999/actionapp; go mod tidy
      shell: bash
    - run: go run ${{ github.action_path }}/. ${{ inputs.path }}  
      shell: bash
      env:
        INPUT_TEST_API_KEY: ${{ inputs.key }}
        INPUT_TEST_SPACE: ${{ inputs.space }}
